insert into [LocaleStringResource]([ResourceName], [ResourceValue], [LanguageId])
values ('Admin.Promotions.PartialPayment.List.SearchStartDate', 'Start Date',
        1),
       ('Admin.Promotions.PartialPayment.List.SearchEndDate', 'End Date', 1),
       ('Admin.Promotions.PartialPayment.List.SearchName', 'Name', 1),
       ('Admin.Promotions.PartialPayments.Fields.Name', 'Name', 1),
       ('Admin.Promotions.PartialPayments.Fields.AdminComment', 'Admin Comment',
        1),
       ('Admin.Promotions.PartialPayments.Fields.UsePercentage',
        'Use Percentage', 1),
       ('Admin.Promotions.PartialPayments.Fields.PartialPaymentPercentage',
        'Percentage', 1),
       ('Admin.Promotions.PartialPayments.Fields.PartialPaymentAmount',
        'Amount', 1),
       ('Admin.Promotions.PartialPayments.Fields.MaximumPartialPaymentAmount',
        'Maximum Amount', 1),
       ('Admin.Promotions.PartialPayments.Fields.StartDate', 'Start Date', 1),
       ('Admin.Promotions.PartialPayments.Fields.EndDate', 'End Date', 1),
       ('Admin.Promotions.PartialPayments.Info', 'Partial Payment Info', 1),
       ('Admin.Promotions.PartialPayments.AppliedToProducts',
        'Applied to products', 1),
       ('Admin.Promotions.PartialPayment.History', 'Usage History', 1),
       ('Admin.Promotions.PartialPayments.AppliedToProducts.Product',
        'Product Name', 1),
       ('Admin.Promotions.PartialPayments.AppliedToProducts.AddNew',
        'Apply to a product', 1),
       ('Admin.Promotions.PartialPayments.AppliedToProducts.SaveBeforeEdit',
        'You must save to the partial payment beforing adding product', 1),
       ('Admin.Promotions.PartialPayments.AddNew', 'Add New', 1),
       ('Admin.Promotions.PartialPayments.BackToList', 'Back to list', 1),
       ('Admin.Promotions.PartialPayments.EditPartialPaymentsDetails', 'Edit',
        1),
       ('Admin.Promotions.PartialPayment', 'Partial Payment', 1),
       ('ActivityLog.AddNewPartialPayment', 'Partial Payment {0} added', 1),
       ('Admin.Promotions.PartialPayments.Added',
        'New Partial Payment Inserted', 1),
       ('ActivityLog.EdiPartialPayment', 'Edited Partial Payment {0}', 1),
       ('Admin.Promotions.PartialPayments.Updated', 'Partial Payment Updated',
        1)
        ,
       ('Admin.Promotions.PartialPayments.DuplicateProductError',
        'Product {0} has already been added to a partial payment', 1),

       ('Admin.Promotions.PartialPayments.EditPartialPaymentDetails', 'Edit',
        1),

       ('Admin.CustomerWallet.PartialPayments', 'Partial Payments', 1),
       ('Admin.CustomerWallet.CustomerWallets', 'Customer Wallets', 1),
       ('Admin.CustomerWallet.PartialPaymentUsageHistories',
        'Partial Payment Usage Histories', 1),

       ('Admin.CustomerWallet','Wallets',1)
       
    